name: 625 error

on:
  workflow_dispatch:

jobs:
  build:
    name: Install Temurin 8 on macos
    runs-on: macos-14
    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "11"
