name: 632 error

on:
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            persist-credentials: false
        - name: set up JDK 17
          uses: actions/setup-java@v4.2.0
          with:
            distribution: 'oracle'
            java-version: 17
            check-latest: false
            cache: 'maven'
        - name: Maven Verify
          run: mvn clean compile
  
  codestyle:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: set up JDK 17
          uses: actions/setup-java@v4.2.0
          with:
            distribution: 'oracle'
            java-version: 17
            check-latest: false
            cache: 'maven'
        # - name: Maven Verify
        #   run: mvn checkstyle:check
  
  test:
      needs: codestyle
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: set up JDK 17
          uses: actions/setup-java@v4.2.0
          with:
            distribution: 'oracle'
            java-version: 17
            check-latest: false
            cache: 'maven'
        - name: Maven Verify
          run: mvn -B clean verify
        # - name: Upload coverage reports to Codecov
        #   uses: codecov/codecov-action@v4.0.1
        #   with:
        #     token: ${{ secrets.CODECOV_TOKEN }}
        #     slug: Ivanuil/ImageEditor
