name: 635 PR

on:
  workflow_dispatch:

jobs:
  Jet_Brains_Test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ['ubuntu-latest','windows-latest','macos-13','macos-14']
        jdk: ['17']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: JetBrains Setup Java Test
        uses: gmitch215/setup-java@main
        with:
            distribution: 'jetbrains'
            java-version: ${{matrix.jdk}}
      - name: Verify Java installation
        run: java -version
