name: 673 Error

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest', 'macos-14','macos-13']
        jdk: ['8','11','17','21']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: mahabaleshwars/setup-java@distributions/semuru
        with:
          distribution: 'semeru'
          java-version: ${{ matrix.jdk }}
