name: 890 issue

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: amazonlinux:2023

    steps:
      - name: Install necessary packages
        run: |
          yum update -y
          yum install -y tar
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run commands
        run: |
          echo "Hello, World!"
