name: 890 issue

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: amazonlinux:2023

    steps:

    - name: Checkout code
      uses: actions/checkout@v3
    # - name: Install tar
    #   run:  apt-get install -y tar
    - name: Run commands
      run: |
          echo "Hello, World!"
