name: Corretto Test

on:
  workflow_dispatch:

jobs:
  Corretto_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Corretto
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
