name: GraalVM GPG Test

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: graalvm/setup-java@fniephaus/graalvm
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: maven
      - name: Install GPG
        run: sudo apt-get install -y gnupg2
      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
      - name: Build with Maven
        run: mvn -B package --file pom.xml
