name: GraalVM test

on:
  workflow_dispatch:

jobs:
  GraalVM_Test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: graalvm/setup-java@fniephaus/graalvm
        with:
          distribution: 'graalvm'
          java-version: '17'

      - name: Verify Java installation
        run: java -version
