name: GraalVM Maven Publish
on:
   workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: graalvm/setup-java@fniephaus/graalvm
      with:
        distribution: 'zulu'
        java-version: '21'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Publish to GitHub Packages
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
