name: 673 Error

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ${{ matrix.os }}-${{ matrix.arch }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        jdk: ['8', '11', '17', '21']
        arch: ['ccd']  # Add the architecture options here
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: mahabaleshwars/setup-java@distributions/semuru
        with:
          distribution: 'semeru'
          java-version: ${{ matrix.jdk }}
