name: Shared Deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  ENVIRONMENT: ${{ inputs.ENVIRONMENT }}

jobs:

  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          check-latest: true
      - name: Install Java
        run: |
            apk update && \
            apk upgrade
            apk add openjdk11=11.0.24_p8-r0

      - name: Semgrep Scan
        run: |
          chmod +x $JAVA_HOME/bin/java
          echo "Path is: $PATH"
          echo "JAVA_HOME is: $JAVA_HOME"
          echo "JAVA_HOME_21_X64 is $JAVA_HOME_21_X64"
          echo "Which Java? $(which java)"
          echo "Which Java version?"
          java -version
          echo "What files are found in $JAVA_HOME_21_X64/bin?"
          ls -la $JAVA_HOME_21_X64/bin
          echo "What files are found in $JAVA_HOME/bin?"
          ls -la $JAVA_HOME/bin
          echo "Testing specific java binary:"
          $JAVA_HOME_21_X64/bin/java -version
