name: Shared Deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  ENVIRONMENT: ${{ inputs.ENVIRONMENT }}

jobs:

  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          check-latest: true
      - name: Install Java
        run: |
            apk update && \
            apk upgrade
            apk add openjdk21

      - name: Semgrep Scan
        run: |
            which java
            type java
            echo $JAVA_HOME
            echo $PATH
            java --help
