name: issue793

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
       
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: gowridurgad/setup-java@error-handling
        with:
          java-version: '11'
          distribution: 'adopt' 
          check-latest: true
         
