name: 673 Error

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        
       
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: gowridurgad/setup-java-fork@testing-schema
        with:
          java-version: '21'
          distribution: 'temurin' 
         
