name: 953issue

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        
       
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'corretto' 
