name: Test all distributions with CRaC

on:
  push:
  workflow_dispatch:

jobs:
  test-java-crac:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: 
          # - temurin
          - zulu
          # - adopt
          # - adopt-hotspot
          # - adopt-openj9
          - liberica
          # - corretto
        
     
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Java with CRaC
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        java-package: 'jdk+crac'
        distribution: ${{ matrix.distribution }}

    - name: Verify Java version
      run: java -version

    # - name: Run your tests
    #   run: ./gradlew test  # Replace with your actual test command
