name: Java Multiple JDK Demo

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-20.04 
    strategy:
      matrix:
        java: [ '17'] 
    name: Java ${{ matrix.Java }} sample
    steps:
      - uses: actions/checkout@v4
      - name: Setup java action
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          # java-version: ${{ matrix.java }}
          java-version-file: '.java-version'
          cache: "maven"
          check-latest: true
      - name: Setup java
        uses: mahabaleshwars/setup-java@add-tool-version-file-support
        with:
          distribution: 'microsoft'
          # java-version: ${{ matrix.java }}
          java-version-file: '.java-version'
          cache: "maven"
          check-latest: true
         
      
