name: Java Tool Version File Testing
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution: ['zulu', 'adopt', 'adopt-openj9']
        version: [15-ea, 15.0.0-ea]
    name: Java sample
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4
      - name: Setup-Java 
        uses: actions/setup-java@v4
        with:
          distribution: ${{matrix.distribution}}
          java-version: ${{matrix.version}}
