name: Java Tool Version File Testing
on:
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        version: [zulu,microsoft,temurin,adopt,oracle,coretto,semuru,dragonwell,liberica]
    runs-on: ubuntu-latest
    name: Java sample
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: mahabaleshwars/setup-java@add-tool-version-file-support
        with:
          distribution: ${{matrix.version}}
          java-version: 15.0.0-ea.2
       
