name: Publish Maven package to GPR

on:
  push:
    branches: [ "GPR" ]
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  

  
    - name: Set up Apache Maven Central
      uses: gowridurgad/setup-java-fork@testing-snap
      with: # running setup-java again overwrites the settings.xml
        distribution: 'sapmachine'
        java-version: '11'
        server-id: central # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: 2pAf009I # env variable for username in deploy
        server-password: +2sXhEf/0Y5rYV3qQk6Y4RSNM1ntfPpfXIPwBKLa8bHr # env variable for token in deploy
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

    - name: Publish to Apache Maven Central
      run: mvn deploy
      env:
        MAVEN_USERNAME: 2pAf009I
        MAVEN_CENTRAL_TOKEN: +2sXhEf/0Y5rYV3qQk6Y4RSNM1ntfPpfXIPwBKLa8bHr
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
