name: setup java 600

on:
 push
    
    
jobs:
  build_4_0_0:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '17']   
    name: Java ${{ matrix.Java }} sample
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup java
        uses: actions/setup-java@v4.0.0
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'oracle'
          cache: 'maven'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
  build_4_1_0:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '17']   
    name: Java ${{ matrix.Java }} sample
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup java
        uses: actions/setup-java@v4.1.0
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'oracle'
          cache: 'maven'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}     
  build_4_2_0:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '17']   
    name: Java ${{ matrix.Java }} sample
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup java
        uses: actions/setup-java@v4.2.0
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'oracle'
          cache: 'maven'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
     
