name: Java Multiple JDK Demo

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-20.04 
    strategy:
      matrix:
        java: [ '17']
    name: Java ${{ matrix.Java }} sample
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: ${{ matrix.java }}
          cache: "maven"
          check-latest: true
          # cache-dependency-path: 'pom.xml'
      - name: Build with Maven
        run: mvn clean install

