name: Java Tool Version File Testing
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Java sample
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: mahabaleshwars/setup-java@test-for-java-version
        with:
          distribution: microsoft
          java-version-file: ./src/main/.tool-versions
       
