name: Java Multiple JDK Demo

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04 
    
    name: Java ${{ matrix.Java }} sample
    
    steps:
      - name: 'Set up archived Oracle JDK 17.0.1'
      - uses: actions/setup-java@v4
        with:
          distribution: '<distribution>'
          java-version: |
            8
            11
            15
