name: Java Tool Version File Testing
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Java sample
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
