name: Java Multiple JDK Demo

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04 
    
    name: Java ${{ matrix.Java }} sample
    
    steps:
      - name: 'Set up archived Oracle JDK 17.0.1'
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 17
          version: 17.0.1
    
