name: setup java 600

on:
 push
    
    
jobs:
  build:
    runs-on: ubuntu-20.04 
    strategy:
      matrix:
        java-version: [ '17']
        
    name: Java ${{ matrix.Java }} sample
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'oracle'
          #server-id: github_token
          #settings-path: ${{ github.workspace }}
          cache: 'maven'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Build with Maven
        run: mvn clean install

