name: setup java 600

on:
 push
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ '17']   
    name: Java ${{ matrix.Java }} sample
    steps:
      - uses: actions/checkout@v4.0.0
      
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'oracle'
          cache: 'maven'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
     