name: Java Multiple JDK Demo

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-20.04 
    strategy:
      matrix:
        java: [ '17'] 
    name: Java ${{ matrix.Java }} sample
    steps:
      - name: Setup java
        uses: mahabaleshwars/setup-java@main
        with:
          distribution: 'microsoft'
          # java-version: ${{ matrix.java }}
          java-version-file: '.tool-versions'
          cache: "maven"
          check-latest: true
          # cache-dependency-path: 'pom.xml'
      - name: Build with Maven
        run: mvn clean install
