name: Konf CI
on: [ push ]
jobs:
  build:
    name: Build on JDK ${{ matrix.java_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Only covers Java 21 because the publishing plugin doesn't work on lesser versions
        java_version: [ 21.0.3 , 21.0.2, 20.0, 19.0, 21.0.2, 21.0]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'zulu'
          


      # - name: Build without Daemon
      #   run: ./gradlew build --no-daemon
      # - name: Stop Gradle Daemon
      #   run: ./gradlew --stop  
     
      # - name: Report Coveralls (Windows)
      #   if: startsWith(runner.os, 'Windows')
      #   run: |
      #     Invoke-WebRequest -Uri "https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-windows.zip" -OutFile "coveralls-windows.zip"
      #     Add-Type -AssemblyName System.IO.Compression.FileSystem
      #     [System.IO.Compression.ZipFile]::ExtractToDirectory("coveralls-windows.zip", ".")
      #     Remove-Item "coveralls-windows.zip"
      #     Start-Process -FilePath ".\coveralls.exe" -ArgumentList "report build/reports/kover/report.xml" -NoNewWindow -Wait
      #   env:
      #     COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
     
