name: Java Multiple JDK Demo

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04 
    
    name: Java sample
    
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'x64'
          java-version: |
            8
            11
            15
