name: Java Multiple JDK Demo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: Java sample
    steps:
    - name: Setting Microsoft JDK with caching
      uses: mahabaleshwars/setup-java@add-tool-version-file-support
      with:
        distribution: microsoft
        java-version-file: .tool-versions


