name: Java Multiple JDK Demo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: Java sample
    steps:
    - name: Setting Microsoft JDK with caching
      uses: mahabaleshwars/setup-java-arm64@main
      with:
        java-version: 17
        distribution: microsoft
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
      
