name: Publish Maven package to GPR

on:
  push:
    branches: [ "GPR" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Apache Maven Central
      uses: gowridurgad/setup-java-fork@testing-snap
      with: # running setup-java again overwrites the settings.xml
        distribution: 'sapmachine'
        java-version: '11'
        server-id: central # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME # env variable for username in deploy
        server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

    - name: "Check gpg setup"
      shell: bash
      run: |
        gpg --version
        gpg --list-keys
        gpg --list-secret-keys

    - name: "Check gpg setup on Linux"
      if: runner.os == 'Linux'
      shell: bash
      run: |
        which gpg
        cat /home/runner/.m2/settings.xml

    - name: "Check gpg setup on macOs"
      if: runner.os == 'macOs'
      shell: bash
      run: |
        which gpg
        cat /Users/runner/.m2/settings.xml

    - name: "Check gpg setup on Windows"
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        where.exe gpg
        cat C:\Users\runneradmin\.m2\settings.xml

    - name: "Set maven-gpg-plugin.version to v${{ matrix.gpg-plugin-version }}"
      shell: bash
      run: |
        ./mvnw --batch-mode --show-version versions:set-property -D "property=maven-gpg-plugin.version" -D "newVersion=${{ matrix.gpg-plugin-version }}"

    - name: "Build and sign"
      shell: bash
      run: |
        ./mvnw --batch-mode --show-version clean verify

    - name: Publish to Apache Maven Central
      run: mvn -P release --batch-mode deploy -DskipTests
      env:
        MAVEN_USERNAME: +ZArALIw
        MAVEN_CENTRAL_TOKEN: HiFxjNaL7H9uvVzZ5W+w8ssoG5dAaJgw8D4Av1WzdvGg
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}