name: Publish Maven package to GPR

on:
  push:
    branches: [ "GPR" ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: gowridurgad/setup-java-fork@testing-snap
        with:
          java-version: '11'
          distribution: 'sapmachine'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: Rs1iL1A5
          MAVEN_PASSWORD: MZyVegKF/CfLc1fLrag/iskTiJqx3DKH30WWzL5eHl/T