name: Java Tool Version File Testing
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [15-ea, 15.0.0-ea, 15.0.0-ea.2, 15.0.0+2-ea]
        os: ['microsoft', 'zulu', temurin', 'oracle', 'adopt', 'adopt-openj9', 'liberica', 'corretto', 'semeru', 'dragonwell']
    name: Java sample
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4
      - name: Setup-Java 
        uses: actions/setup-java@v4
        with:
          distribution: matrix.os
          java-version: matrix.version
