name: mavenPR5

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
        
       
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: mahabaleshwars/setup-java@feature/cache-maven-wrapper
        with:
          java-version: '21'
          distribution: 'temurin' 
          cache: maven
