name: Java Tool Version File Testing
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Java sample
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4
      - name: Setup-node 
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
      - run: npm ci
      - run: npm test
