name: testing-1008

on:
  workflow_dispatch:

jobs:
  discover:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - temurin
          - zulu
          - corretto
          - microsoft
          - oracle
          - liberica
          - sapmachine
          - jetbrains

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: ${{ matrix.distribution }}
          java-version: '17'
          check-latest: true

      
