name: testing530

on: [workflow_dispatch]

jobs:
  test-toolchains-duplication:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 
        uses: Okeanos/setup-java@fix-maven-toolchains-duplication
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Print toolchains.xml
        run: cat ~/.m2/toolchains.xml

     
        
