name: testing-1008

on:
  workflow_dispatch:

jobs:
  discover:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - distribution: temurin
            java-version: '17.0.19+10'
          - distribution: zulu
            java-version: '17.0.19+10'
          - distribution: corretto
            java-version: '17.0.19'
          - distribution: microsoft
            java-version: '17.0.10'
          - distribution: oracle
            java-version: '17'
          - distribution: liberica
            java-version: '17.0.19+11'
          - distribution: sapmachine
            java-version: '17.0.19'
          - distribution: jetbrains
            java-version: '17.0.14+1367.22'

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        # uses: actions/setup-java@v5
        uses: sproctor/setup-java@main 
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java-version }}
   

      
